# Analyze Best Selling Amazon Books with Pandas

# Introduction---Python is a powerful programming language that can be used for a variety of tasks, including analyzing data from a CSV file. We'll go over how to use Python to import data and run an analysis on it. We'll be using the pandas library, a popular data analysis tool for Python.
Amazon Best Sellers are updated every hour. The actual list is made of 100 books, but the data we're working with features just the top 50 books. 📖
The .csv file contains 550 books. Here are the seven columns:
Name: Book name
Author: Book author
User Rating: Amazon user rating (0.0 - 5.0)
Reviews: Number of user reviews
Price: Book price (as of 2020)
Year: The year(s) it ranked
Genre: Fiction or non-fiction

# Step 1-Import the Libraries

In [1]:
import pandas as pd

# Step 2-Import pandas and Load the Spreadsheet

In [4]:
df=pd.read_csv("bestsellers with categories.csv")
df

,Name,Author,User Rating,Reviews,Price,Year,Genre
0,10-Day Green Smoothie Cleanse,JJ Smith,4.7,17350,8,2016,Non Fiction
1,11/22/63: A Novel,Stephen King,4.6,2052,22,2011,Fiction
2,12 Rules for Life: An Antidote to Chaos,Jordan B. Peterson,4.7,18979,15,2018,Non Fiction
3,1984 (Signet Classics),George Orwell,4.7,21424,6,2017,Fiction
4,"5,000 Awesome Facts (About Everything!) (Natio...",National Geographic Kids,4.8,7665,12,2019,Non Fiction
...,...,...,...,...,...,...,...
545,Wrecking Ball (Diary of a Wimpy Kid Book 14),Jeff Kinney,4.9,9413,8,2019,Fiction
546,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2016,Non Fiction
547,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2017,Non Fiction
548,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2018,Non Fiction
549,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2019,Non Fiction

# Step 3: Explore the Data

In [5]:
df.head()

,Name,Author,User Rating,Reviews,Price,Year,Genre
0,10-Day Green Smoothie Cleanse,JJ Smith,4.7,17350,8,2016,Non Fiction
1,11/22/63: A Novel,Stephen King,4.6,2052,22,2011,Fiction
2,12 Rules for Life: An Antidote to Chaos,Jordan B. Peterson,4.7,18979,15,2018,Non Fiction
3,1984 (Signet Classics),George Orwell,4.7,21424,6,2017,Fiction
4,"5,000 Awesome Facts (About Everything!) (Natio...",National Geographic Kids,4.8,7665,12,2019,Non Fiction

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 550 entries, 0 to 549
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Name         550 non-null    object
 1   Author       550 non-null    object
 2   User Rating  550 non-null    float64
 3   Reviews      550 non-null    int64
 4   Price        550 non-null    int64
 5   Year         550 non-null    int64
 6   Genre        550 non-null    object
dtypes: float64(1), int64(3), object(3)
memory usage: 30.2+ KB

In [7]:
df.describe()

       User Rating       Reviews       Price         Year
count   550.000000    550.000000  550.000000   550.000000
mean      4.618364  11953.281818   13.100000  2014.000000
std       0.226980  11731.132017   10.842262     3.165156
min       3.300000     37.000000    0.000000  2009.000000
25%       4.500000   4058.000000    7.000000  2011.000000
50%       4.700000   8580.000000   11.000000  2014.000000
75%       4.800000  17253.250000   16.000000  2017.000000
max       4.900000  87841.000000  105.000000  2019.000000

In [8]:
df.tail

<bound method NDFrame.tail of                                                   Name  \
0                        10-Day Green Smoothie Cleanse
1                                    11/22/63: A Novel
2              12 Rules for Life: An Antidote to Chaos
3                               1984 (Signet Classics)
4    5,000 Awesome Facts (About Everything!) (Natio...
..                                                 ...
545       Wrecking Ball (Diary of a Wimpy Kid Book 14)
546  You Are a Badass: How to Stop Doubting Your Gr...
547  You Are a Badass: How to Stop Doubting Your Gr...
548  You Are a Badass: How to Stop Doubting Your Gr...
549  You Are a Badass: How to Stop Doubting Your Gr...

                       Author  User Rating  Reviews  Price  Year        Genre
0                    JJ Smith          4.7    17350      8  2016  Non Fiction
1                Stephen King          4.6     2052     22  2011      Fiction
2          Jordan B. Peterson          4.7    18979     15  2018  Non Fiction
3               George Orwell          4.7    21424      6  2017      Fiction
4    National Geographic Kids          4.8     7665     12  2019  Non Fiction
..                        ...          ...      ...    ...   ...          ...
545               Jeff Kinney          4.9     9413      8  2019      Fiction
546               Jen Sincero          4.7    14331      8  2016  Non Fiction
547               Jen Sincero          4.7    14331      8  2017  Non Fiction
548               Jen Sincero          4.7    14331      8  2018  Non Fiction
549               Jen Sincero          4.7    14331      8  2019  Non Fiction

[550 rows x 7 columns]>

In [10]:
df.isnull().sum()

Name           0
Author         0
User Rating    0
Reviews        0
Price          0
Year           0
Genre          0
dtype: int64

In [12]:
df.shape

(550, 7)

In [14]:
df.columns

Index(['Name', 'Author', 'User Rating', 'Reviews', 'Price', 'Year', 'Genre'], dtype='object')

These functions will give us a good overview of the data we're working with, including:

The size of the data
The column names
Summary statistics for each column

# Step 4: Clean the Data

The first thing we can do is check for and remove any duplicate rows in the dataset using the drop_duplicates() function.

In [15]:
df.drop_duplicates(inplace=True)

#Renaming Columns
Next, we can rename the columns of the DataFrame to make them more descriptive and easier to work with. We can use the rename() function to do this.

In [17]:
df.rename(columns={"Name": "Title", "Year": "Publication Year", "User Rating": "Rating"}, inplace=True)

This code renames the "Name" column to "Title" and the "Year" column to "Publication Year". Again, by setting the inplace parameter to True, the changes are made directly to the original DataFrame.

## Converting Data Types
Finally, we can convert the "Price" column to a float data type to make it easier to work with. We can use the astype() function to do this.

In [18]:
df["Price"] = df["Price"].astype(float)

This code converts the "Price" column to a float data type. Note that we select the "Price" column of the DataFrame using the square bracket notation, and then apply the astype() function to it. The resulting values are then stored back in the "Price" column of the DataFrame.

After performing these cleaning operations, our DataFrame should be ready for analysis.

# Step 5: Run an Analysis

## Analyzing Author Popularity
Using methods from our df DataFrame object, we can get a glimpse of which authors have the most books on the Amazon Best Sellers list.

This can be done by selecting the 'Author' column data and using the value_counts() method. We can assign this to an author_counts variable:

In [19]:
author_counts = df['Author'].value_counts()
print(author_counts)

Author
Jeff Kinney                           12
Gary Chapman                          11
Rick Riordan                          11
Suzanne Collins                       11
American Psychological Association    10
                                      ..
Keith Richards                         1
Chris Cleave                           1
Alice Schertle                         1
Celeste Ng                             1
Adam Gasiewski                         1
Name: count, Length: 248, dtype: int64

## Average Rating by Genre
We can also use the cleaned data to determine the average rating for each genre in the dataset. We can do this by grouping the data by the "Genre" column and calculating the mean of the "Rating" column

In [21]:
avg_rating_by_genre = df.groupby("Genre")["Rating"].mean()
print(avg_rating_by_genre)

Genre
Fiction        4.648333
Non Fiction    4.595161
Name: Rating, dtype: float64

This code groups the data by the "Genre" column, and then calculates the mean of the "Rating" column for each genre. It then prints the resulting series of average ratings by genre.

# Step 6: Export the Results

Finally, once we have performed our analysis and obtained some insights from the data, we may want to export the results to a file for further analysis or sharing with others. We can use the to_csv() function to export our cleaned and analyzed DataFrame to a CSV file.

In [22]:
# Export top selling authors to a CSV file
author_counts.head(10).to_csv("top_authors.csv")

# Export average rating by genre to a CSV file
avg_rating_by_genre.to_csv("avg_rating_by_genre.csv")

This will export the top 10 selling authors and the average rating by genre to a separate .csv files.

By default, these files will be saved in the same directory as our main.py file. We can specify a different directory by providing a file path instead of just a file name.

# Conclusion

We were able to harness the power of Python libraries like pandas to analyze data from a CSV file. Specifically, we did the following:

Imported book data about the top 50 books on Amazon from 2009 to 2019.
Explored and cleaned the data with DataFrame methods.
Exported the modified data to a new CSV file